
#--- spring
spring: 
  profiles:
    active: local
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
    request-context-attribute: rc
  jackson:
    serialization:
      write_dates_as_timestamps: false

#--- jpa
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

#--- datasource
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/test?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: test
    password: test1234

#--- redis
  redis:
    host: localhost
    port: 6379
    
#--- server
server:
  error:
    whitelabel:  
      enabled: true

#--- loggin
logging:
  config: classpath:log.xml 
  
#--- path
path:
  image: ./src/main/webapp/static/images/